<?php
$to=false;
$msg=mb_substr(htmlspecialchars(trim($arg['msg']), ENT_QUOTES, 'utf-8'),0,500,'utf-8');
if($this->char['_id']&&$msg)
{
	$rl=0;
	if(in_array($arg['ty'],array('map','shout','guild','private')))
	{
		$ty=$arg['ty'];
	}
	else
	{
		$ty='map';	
	}
	$valid=true;
	
	if(substr($msg,0,1)=='/')
	{
		if(in_array(_::$my['_id'],array(1,19617,57290,19255,1162,33127)))
		{
			$ty='';
			$valid=false;
			$cmd=explode(' ',$msg);
			if($cmd[0]=='/item')
			{
				$item=intval($cmd[1]);
				if($item)
				{
					$items=$this->config('item');
					if($items[$item])
					{
						if($items[$item]['type']<=1||$items[$item]['type']==10)
						{
							$count=max(intval($cmd[2]),1);
						}
						else
						{
							$count=1;
						}
						$op=array('slot'=>0,'ele'=>0);
						if($items[$item]['can_ele'])
						{
							$op['slot']=1;	
						}
						$this->item_insert(_::$my['_id'],$item,$count,false,$op);
						$this->update_inventory();	
					}
				}
			}
			elseif($cmd[0]=='/silver')
			{
				$silver=intval($cmd[1]);
				if($silver)
				{
					$this->char['silver']+=$silver;
					$this->db->update('lionica_char',array('_id'=>$this->char['_id']),array('$inc'=>array('silver'=>$silver)));
				}
			}
			elseif($cmd[0]=='/change')
			{
				$nh=intval($cmd[1]);
				$ele=intval($cmd[2]);
				for($i=2;$i<=6;$i++)
				{
					if($it=$this->char['eq']['i'.$i])
					{
						//inv
						$this->db->update('lionica_item',array('u'=>_::$my['_id'],'_id'=>$it['inv']),array('$set'=>array('nh'=>$nh)));
						
						if($ele)
						{
							if($i==2||$i==3)
							{
								$this->db->update('lionica_item',array('u'=>_::$my['_id'],'_id'=>$it['inv']),array('$set'=>array('ele'=>$ele)));
							}
						}
					}
				}
			}
			elseif($cmd[0]=='/pet')
			{
				if($this->char['pet'])
				{
					if(in_array($cmd[1],array('str','agi','vit','dex','int')))
					{
						$inc=min(10,max(intval($cmd[2]),1));
						$this->db->update('lionica_char',array('_id'=>$this->char['_id']),array('$set'=>array('pet.status.type'=>$cmd[1],'pet.status.inc'=>$inc)));
						//$insert['status']=array('hp'=>100,'mhp'=>100,'lv'=>1,'xp'=>0,'mxp'=>100,'ele'=>$id-313,'evo'=>0,'type'=>$sta[0],'inc'=>$inc[0]);
					}
					elseif(in_array($cmd[1],array('lv','hp')))
					{
						$inc=max(intval($cmd[2]),1);
						$this->db->update('lionica_char',array('_id'=>$this->char['_id']),array('$set'=>array('pet.status.'.$cmd[1]=>$inc)));
					}
				}
			}
			elseif($cmd[0]=='/exp')
			{
				$exp=intval($cmd[1]);
				if($exp)
				{
					$this->char['xp']+=$exp;
					$this->db->update('lionica_char',array('_id'=>$this->char['_id']),array('$inc'=>array('xp'=>$exp)));
				}
			}
		}
	}
	if($ty=='guild')
	{
		if(!$this->char['g'])
		{
			_::ajax()->script('_.lionica.notice("คุณยังไม่มีกิลด์")');
			$valid=false;	
		}
		else
		{
			$rl=$this->char['g']['_id'];	
		}
	}
	elseif($ty=='shout')
	{
		if(!$inv=$this->db->findone('lionica_item',array('item'=>307,'u'=>_::$my['_id'])))
		{
			$this->ajax->script('_.lionica.notice("คุณไม่มี Megaphone (หาซื้อได้จากร้านค้า)")');
			$valid=false;	
		}
		else
		{
			if($inv['c']>1)
			{
				$this->db->update('lionica_item',array('_id'=>$inv['_id']),array('$inc'=>array('c'=>-1)));
			}
			else
			{
				$this->db->remove('lionica_item',array('_id'=>$inv['_id']));
			}
			$this->update_inventory();
		}
	}
	elseif($ty=='private')
	{
		if($arg['to'])
		{
			if(!$to=$this->db->findone('lionica_char',array('_id'=>intval($arg['to'])),array('_id'=>1,'du'=>1,'n'=>1)))
			{
				$this->ajax->script('_.lionica.notice("ไม่มีบุคคลที่ต้องการส่งถึง")');
				$valid=false;	
			}
			elseif(!$to['du'] || $to['du']->sec<time()-120)
			{
				$this->ajax->script('_.lionica.notice("บุคคลดังกล่าวออฟไลน์ไปแล้ว")');
				$valid=false;	
			}
			else
			{
				$rl=array('p'=>$to['_id'],'n'=>$to['n']);
			}
		}
	}
	else
	{
		$rl=$this->map['_id'];	
	}
	
	if($valid)
	{
		$time=microtime(true);
		$this->map['chat'][]=array('_id'=>$time,'ty'=>$ty,'rl'=>$rl,'p'=>$this->char['_id'],'t'=>$msg,'n'=>$this->char['n'],'l'=>_::$my['link'],'tm'=>date('H:i'),'_sn'=>str_replace('.','_','tm_'.$time));
		
		if(count($this->map['chat'])>40)
		{
			$this->map['chat']=array_slice($this->map['chat'],20);
		}
		_::cache()->set('ca2','lionica_chat',$this->map['chat'],false,3600*24);
	}
}

?>