<?php

Load::Ajax()->register(['delcustomer','newcustomer']);

Load::$core->data['title']='ข้อมูลลูกค้า | '.Load::$core->data['title'];

$tmp=$db->find('team_user',[],[],['sort'=>['code'=>1]]);
$people=[];
for($i=0;$i<count($tmp);$i++)
{
  $people[$tmp[$i]['_id']]=$tmp[$i];
}
$tmp=$db->find('team_customer',['dd'=>['$exists'=>false]],[],['sort'=>['parent'=>0,'name'=>1]]);
$customer=[];
for($i=0;$i<count($tmp);$i++)
{
  $c=$tmp[$i];
  if(!$c['parent'])
  {
    $c['sub']=[];
    $customer[$c['_id']]=$c;
  }
  else
  {
    $customer[$c['parent']]['sub'][]=$c;
  }
}
Load::$core->data['content']=Load::$core->assign('customer',$customer)
                ->assign('people',$people)
                ->fetch('customer.home');


function delcustomer($i)
{
  $arg=['_id'=>intval($i),'u'=>team::$my['_id']];
  if(team::$my['grade']==99)
  {
    unset($arg['u']);
  }
  Load::DB()->update('team_customer',$arg,['$set'=>['dd'=>Load::Time()->now(),'ud'=>team::$my['_id']]]);
  team::move(URL);
}

function newcustomer($par)
{
  $arg=[];
  //$arg['by']=intval($par['by']);
  $arg['name']=trim($par['name']);
  /*
  $arg['type']=intval($par['type']);
  $arg['tax']=trim($par['tax']);
  $arg['parent']=intval($par['parent']);
  $arg['sub_tax']=trim($par['sub_tax']);
  $arg['address']=trim($par['address']);
  $arg['service']=intval($par['service']);
  $arg['approve']=['status'=>0,'u'=>0];
  $arg['lock']=['status'=>0,'u'=>0];
  if(is_array($par['brand']))
  {
    $arg['brand']=array_map('intval',(array)$par['brand']);
  }
  elseif($par['brand'])
  {
    $arg['brand']=array(intval($par['brand']));
  }
  if(is_array($par['sale']))
  {
    $arg['sale']=array_map('intval',(array)$par['sale']);
  }
  elseif($par['sale'])
  {
    $arg['sale']=array(intval($par['sale']));
  }
  $arg['bill']=[
      'billing'=>trim($par['bill_billing']),
      'cheque'=>trim($par['bill_cheque']),
      'cash'=>trim($par['bill_cash']),
      'term'=>trim($par['bill_term']),
      'billing_location'=>trim($par['bill_billing_location']),
      'pay'=>intval($par['bill_pay']),
      'cheque_location'=>trim($par['bill_cheque_location']),
      'how_bill'=>intval($par['bill_how_bill']),
      'email'=>trim($par['bill_email']),
      'doc'=>trim($par['bill_doc']),
  ];

  $arg['contact']=[];
  if(is_array($par['contact_name']))
  {
    for($i=0;$i<count($par['contact_name']);$i++)
    {
      $n=trim($par['contact_name'][$i]);
      $p=trim($par['contact_position'][$i]);
      $e=trim($par['contact_email'][$i]);
      $ph=trim($par['contact_phone'][$i]);
      $f=trim($par['contact_fax'][$i]);
      if($n&&$ph)
      {
        $arg['contact'][]=[
          'name'=>$n,
          'position'=>$p,
          'email'=>$e,
          'phone'=>$ph,
          'fax'=>$f,
        ];
      }
    }
  }
  else
  {
      $n=trim($par['contact_name']);
      $p=trim($par['contact_position']);
      $e=trim($par['contact_email']);
      $ph=trim($par['contact_phone']);
      $f=trim($par['contact_fax']);
      if($n&&$ph)
      {
        $arg['contact'][]=[
          'name'=>$n,
          'position'=>$p,
          'email'=>$e,
          'phone'=>$ph,
          'fax'=>$f,
        ];
      }
  }
  */

  $arg['u']=team::$my['_id'];
  $arg['ue']=team::$my['_id'];
  $arg['de']=Load::Time()->now();
  if($arg['name'])
  {
    $id=Load::DB()->insert('team_customer',$arg);
    team::move('/customer/update/'.$id.'?completed');
  }
}

?>
