<?php
function setstatus($st,$rs='')
{
  global $withdraw;
  $db=Load::DB();
  $ajax=Load::Ajax();
  $st=intval($st);
  if($withdraw['status']==0)
  {
    if($st==1)
    {
      if(Load::DB()->count('team_withdraw_data',['withdraw'=>$withdraw['_id']])>0)
      {
        Load::DB()->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>['status'=>$st,'status1.d'=>Load::Time()->now(),'status1.u'=>team::$my['_id']]]);
      }
      else
      {
        $ajax->alert('ยังไม่มีรายการที่ต้องการเบิก');
        return;
      }
    }
    else
    {
      $ajax->alert('สถานะไม่ถูกต้อง');
    }
    team::move('/withdraw/'.$withdraw['_id']);
  }
  elseif($withdraw['status']==1)
  {
    if($st==2)
    {
      $db->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>[
                                                                      'status'=>$st,
                                                                      'note.c'=>trim($rs),
                                                                      'status2.d'=>Load::Time()->now(),
                                                                      'status2.u'=>team::$my['_id']
                                                                    ]]);
    }
    elseif($st==3)
    {
      $db->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>[
                                                                      'status'=>$st,
                                                                      'status3.d'=>Load::Time()->now(),
                                                                      'status3.u'=>team::$my['_id']
                                                                      ]]);
    }
    else
    {
      $ajax->alert('สถานะไม่ถูกต้อง');
    }
    team::move('/withdraw/'.$withdraw['_id']);
  }
  elseif($withdraw['status']==3)
  {
    if($st==4)
    {
      $db->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>[
                                                                      'status'=>$st,
                                                                      'note.uh'=>trim($rs),
                                                                      'status4.d'=>Load::Time()->now(),
                                                                      'status4.u'=>team::$my['_id']
                                                                    ]]);
    }
    elseif($st==5)
    {
      $set=[
          'status'=>$st,
          'status5.d'=>Load::Time()->now(),
          'status5.u'=>team::$my['_id']
      ];
      if(!$withdraw['no'])
      {
        $cmount=$db->count('team_withdraw',['status5.d'=>['$gte'=>Load::Time()->from(date('Y-m').'-01'),'$lte'=>Load::Time()->from(date('Y-m-t'))]]);
        $cyear=$db->count('team_withdraw',['status5.d'=>['$gte'=>Load::Time()->from(date('Y').'-01-01'),'$lte'=>Load::Time()->from(date('Y').'-12-31')]]);
        $set['no']='AD. '.date('m').'-'.substr(date('Y')+543, -2).'-'.substr('000'.($cmount+1),-3).'-'.substr('00000'.($cyear+1),-5);
      }
      $db->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>$set]);
    }
    else
    {
      $ajax->alert('สถานะไม่ถูกต้อง');
    }
    team::move('/withdraw/'.$withdraw['_id']);
  }
  elseif($withdraw['status']==5)
  {
    if($st==6)
    {
      $db->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>[
                                                                      'status'=>$st,
                                                                      'status6.d'=>Load::Time()->now(),
                                                                      'status6.u'=>team::$my['_id']
                                                                      ]]);
    }
    elseif($st==8)
    {
      $db->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>[
                                                                      'status'=>$st,
                                                                      'status8.d'=>Load::Time()->now(),
                                                                      'status8.u'=>team::$my['_id']
                                                                      ]]);
    }
    else
    {
      $ajax->alert('สถานะไม่ถูกต้อง');
    }
    team::move('/withdraw/'.$withdraw['_id']);
  }
  elseif($withdraw['status']==6)
  {
    if($st==7)
    {
      $db->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>[
                                                                      'status'=>$st,
                                                                      'status7.d'=>Load::Time()->now(),
                                                                      'status7.u'=>team::$my['_id']
                                                                      ]]);
    }
    else
    {
      $ajax->alert('สถานะไม่ถูกต้อง');
    }
    team::move('/withdraw/'.$withdraw['_id']);
  }
  elseif($withdraw['status']==7)
  {
    if($st==8)
    {
      $db->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>[
                                                                      'status'=>$st,
                                                                      'status8.d'=>Load::Time()->now(),
                                                                      'status8.u'=>team::$my['_id']
                                                                      ]]);
    }
    elseif($st==6)
    {
      $db->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>[
                                                                      'status'=>$st,
                                                                      'status8.dc'=>Load::Time()->now(),
                                                                      'status8.uc'=>team::$my['_id']
                                                                      ]]);
    }
    else
    {
      $ajax->alert('สถานะไม่ถูกต้อง');
    }
    team::move('/withdraw/'.$withdraw['_id']);
  }
}

function setrealprice($pam)
{
  global $withdraw;
  if($withdraw['status']==6)
  {
      $price=0;
      $db=Load::DB();
      $db->update('team_withdraw_data',['withdraw'=>$withdraw['_id'],'_id'=>intval($pam['data'])],['$set'=>['price_real'=>floatval($pam['price_real']),'remark_real'=>trim($pam['remark_real'])]]);
      if($sum=$db->find('team_withdraw_data',['withdraw'=>$arg['withdraw']],['price_real'=>1]))
      {
        for($i=0;$i<count($sum);$i++)
        {
          $price+=floatval($sum[$i]['price_real']);
        }
      }
      $db->update('team_withdraw',['_id'=>$withdraw['_id']],['$set'=>['price.real'=>$price]]);
  }
  Load::Ajax()->jquery('#getdata','html',getdata());
}
?>
